---
  # - name: bootstrap first manager node if needed
  #   run_once: true
  #   command: >
  #     docker swarm init
  #     {% for parameter in swarm_cluster_bootstrap_parameters %}
  #       {{ parameter }} {{ swarm_cluster_bootstrap_parameters[parameter] }}
  #     {% endfor %}
- name: "get docker info"
  shell: docker info
  register: docker_info
  changed_when: false

- name: initialise docker swarm
  shell: docker swarm init --advertise-addr "{{ ansible_default_ipv4['address'] }}"
  when: "docker_info.stdout.find('Swarm: inactive') != -1"

- name: register manager token
  shell: docker swarm join-token -q manager
  register: manager_token
  changed_when: false

- name: register worker token
  shell: docker swarm join-token -q worker
  register: worker_token
  changed_when: false

- name: join swarm as manager
  shell: "docker swarm join --token {{ hostvars[swarm_manager_init_host]['manager_token']['stdout'] }} {{ hostvars[swarm_manager_init_host]['ansible_eth0']['ipv4']['address'] }}:2377"
  when: "docker_info.stdout.find('Swarm: inactive') != -1 and not (swarm_init | default(false)) | bool"
  retries: 3
  delay: 20
